version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
  riftarena:
    image: ${DOCKER_REGISTRY-}riftarena
    build:
      context: .
      dockerfile: RiftARENA/Dockerfile
    depends_on:
      - db